### PR TITLE
Fix jumping off over void not swapping elytra

### LINKED ISSUE #5: Jumping off above void doesn't swap elytra
This is kinda a big problem if you're exploring the End 😉. I managed to switch to creative mode quickly enough that I didn't lose my items, but other people might not be so lucky and assume they can jump off End islands.

The console is filled with these lines:
```
[23:05:55] [Server thread/INFO]: [elytra_swap]: WTF! Why are you trying to glide below bedrock?
```

I'm working on a PR that should fix this issue!

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #5

### CODE REVIEW

File: src/main/java/net/szum123321/elytra_swap/mixin/PlayerFallCapture.java [hunk 1]
```diff
@@ -37,44 +37,42 @@ protected PlayerFallCapture(EntityType<? extends LivingEntity> type, World world
...
-
-        while(!world.getBlockState(new BlockPos(currentPosition.getX(), height, currentPosition.getZ())).getMaterial().isSolid() && height > -1){
-            height--;
-        }
-
-        if(height <= -1){
-            ElytraSwap.LOGGER.info("WTF! Why are you trying to glide below bedrock?");
-            return -Math.abs(currentPosition.getY()) * 2; //even if you would fly below bedrock it should work :)
+    private float getFallHeight(BlockPos currentPosition) {
+        try (BlockPos.PooledMutable temp = BlockPos.PooledMutable.get(currentPosition.getX(), Math.max(currentPosition.getY(), world.getHeight()), currentPosition.getZ())) {
```
Comment (Szum123321) [inline src/main/java/net/szum123321/elytra_swap/mixin/PlayerFallCapture.java]: You are getting max of world height and player's position and than going down form that but this creates one big problem. What if there are some blocks above player? Than this function returns negative number which is obviously smaller than 5. Please correct that and I'll merge and publish new version.
